apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-bar
spec:
  tls:
  - hosts:
    - test.koudaibook.com
    secretName: default-certs
  rules:
  - host: test.koudaibook.com
    http:
      paths:
      - path: /
        backend:
          serviceName: coffee-svc
          servicePort: 80