apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oauth
config:
  #scopes: read,write
  mandatory_scope: false
  enable_password_grant: true
  global_credentials: true
  provision_key: XUscyiloz2Z19UTV8je4iFvLNGJK00j2
plugin: oauth2
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: team-a
username: goddy
---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: credential-a
consumerRef: team-a
type: oauth2
config:
  name: goddy
  client_id: student-client
  client_secret: student-secret
  redirect_uri: ["http://www.baidu.com"]